### ISSUE TITLE
Finding Adobe Digital Editions (ADE) keys on Linux using Wine

### ISSUE THREAD

**Issue by acaloiaro** [noDRM/DeDRM_tools#13]
### Question / bug report

When Calibre is running on Linux, and thus fetching ADE keys with `wine`, `DeDRM_tools` is unable to find the appropriate `libcrypto` version with which to extract ADE keys. 

# Versions

Wine: `wine-5.0 (Ubuntu 5.0-3ubuntu1)`
Python (Linux): `3.7.11`
Python (wine environment): `3.10.1`
Adobe Digtal Editions: `3.0` 

# Setup

## Install Python and `pyopenssl`

```
WINEPREFIX="$HOME/.wine32" WINEARCH=win32 wine /path/to/python-3.10.1.exe
WINEPREFIX="$HOME/.wine32" WINEARCH=win32 wine cmd /c python -m pip install pyopenssl

# Set windows version to Windows 8.1
WINEPREFIX="$HOME/.wine32" winecfg
```

## Install Adobe Digital Editions

```WINEPREFIX="$HOME/.wine32" WINEARCH=win32 wine /path/to/ADE_3.0_Installer.exe```
 

# Thoughts

This issue appears to be the result of `find_library` misbehaving in a wine environment. For example, one would expect the following to reveal the path to `libc`, but it unable to find it. 

```
WINEPREFIX="$HOME/.wine32" WINEARCH="win32" wine cmd /c python -c "from ctypes.util import find_library; print(find_library(\"c\"))"
=> None
```

### Which version of Calibre are you running?

5.34

### Which version of the DeDRM plugin are you running?

v10.0.2

### Log output

```log
DeDRM v10.0.2: Python3 exec found as wine py.exe -3
DeDRM v10.0.2: Running adobekey.py under Wine
adobekey.py v7.1
Copyright © 2009-2020 i♥cabbages, Apprentice Harper et al.
Traceback (most recent call last):
  File "Z:\home\adriano\.config\calibre\plugins\DeDRM\libraryfiles\adobekey.py", line 713, in <module>
    sys.exit(cli_main())
  File "Z:\home\adriano\.config\calibre\plugins\DeDRM\libraryfiles\adobekey.py", line 627, in cli_main
    keys, names = adeptkeys()
  File "Z:\home\adriano\.config\calibre\plugins\DeDRM\libraryfiles\adobekey.py", line 413, in adeptkeys
    raise ADEPTError("PyCrypto or OpenSSL must be installed")
__main__.ADEPTError: PyCrypto or OpenSSL must be installed
DeDRM v10.0.2: Wine subprocess call error: 1
DeDRM v10.0.2: Found and decrypted 0 key files
Traceback (most recent call last):
  File "calibre_plugins.dedrm.config", line 35, in checkForDeACSMkeys
    from calibre_plugins.deacsm.libadobeAccount import exportAccountEncryptionKeyDER, getAccountUUID
ModuleNotFoundError: No module named 'calibre_plugins.deacsm'
```

**Comment by acaloiaro** [comment]
I've suggested a fairly naive fix that I welcome feedback on: https://github.com/noDRM/DeDRM_tools/pull/14

I call this naive because using the first directory from `sys.path` suffixed with `DLLs` is not what I consider production-worthy. This should be considered nothing more than a proof-of-concept. Note, I have attempted to fix the issue with `find_library` by first calling `os.add_dll_directory` with the path to the stem DLLs directory, to no avail.

**Comment by noDRM** [comment]
Thanks for that issue report / PR. 

I was unable to get it to correctly find that DLL under Wine either, no matter what I tried. 

I did test Wine key retrieval in the past without issues, but I probably had Crypto(dome) installed and it used that instead of OpenSSL. 
Your solution with checking if the path ends with "DLLs" sounded rather hack-y and unreliable, so I instead implemented it in a way to just check all folders in the PATH variable and check if the DLL is actually present in one of them, that should be way more reliable. 

Also, I noticed that the non-OpenSSL code only tried to use Crypto and not Cryptodome and just quickly fixed that, too. 

I'm going to close your PR without merging it, but I've added you as author of my commit d4eddbcf38c7bc75f8071f4e0c84ee7910aee2e0 with the bugfix. Thanks!

If there's any more issues under Wine, feel free to re-open this.

**Comment by acaloiaro** [comment]
Sounds good. The exhaustive `sys.path` check is a sensible approach.
