### ISSUE TITLE
BUG + FIX: AZW decryption fails due to incorrect null check in stylexml2css.py

### ISSUE THREAD

**Issue by grugq** [noDRM/DeDRM_tools#232]
https://github.com/noDRM/DeDRM_tools/blob/e16748e85486f4e7aac0d73b380e272b6712ac01/DeDRM_plugin/stylexml2css.py#L184

If `val` is an empty binary string `b''` then this test fails and `val` is not set to `0`. Then an exception is raised on line 187 when `int(val)` fails because `int(b'')` doesn't work.

The solution is to use modern Python syntax:

```python
if not val:
    val = 0
```

Creating a pull request is far more work than just fixing the line. I suspect there is a deeper issue with an embedded assumption of `str` type for all data from a file; a hold over from the old Python 2 days. There are very probably other bugs lurking in these files.

**Comment by noDRM** [comment]
I wouldn't be surprised if there's more code lurking around in some of the less-popular DRM variants that's only Python2 compatible because it has never been tested since the Python3 migration; but I don't have an easy way to test for that. I'm going to fix the bug you mentioned, thanks for the report.
