### ISSUE TITLE
Suggestion: Add documentation for KFX-Input

### ISSUE THREAD

**Issue by inferno986return** [noDRM/DeDRM_tools#29]
My configuration using Amazon Kindle v1.26 and Calibre 5.35 suddenly stopped working and it looks like Amazon was forcing KFX. If anyone else has this issue give this plugin by jhowell a try: https://www.mobileread.com/forums/showthread.php?t=291290

Once I had this installed I was able to continue converting. I can't find an explicit licence for the code, but perhaps jhowell can be contacted so the plugin can be added to the repository?

**Comment by j-howell** [comment]
> My configuration using Amazon Kindle v1.26 and Calibre 5.35 suddenly stopped working and it looks like Amazon was forcing KFX. If anyone else has this issue give this plugin by jhowell a try: https://www.mobileread.com/forums/showthread.php?t=291290

There are some cases when KFX cannot be avoided where the KFX Input plugin can be useful. However in many cases where Amazon enforces KFX they also use DRM that these tools cannot currently handle.

I recommend that KFX format be avoided for books from Amazon when possible. Methods for doing so that work with even the most recent version of Kindle for PC are described in this MobileRead post: [Dealing with Kindle for PC/Mac 1.19 and KFX in calibre](https://www.mobileread.com/forums/showthread.php?t=283371)

> I can't find an explicit licence for the code, but perhaps jhowell can be contacted so the plugin can be added to the repository?

There is no reason for adding the KFX Input plugin to this repository. It best to keep non-DRM related functionality elsewhere to avoid potential legal problems.

The README for this project already contains a link to the KFX Input plugin. Nothing more is needed as far as I am concerned.

**Comment by TuxSH** [comment]
> I recommend that KFX format be avoided for books from Amazon when possible

When delivered in azw3 format, JPGs (cover, illustrations) have horrendous quality.

**Comment by noDRM** [comment]
Closing this issue as I believe @j-howell said everything that needs to be said. The KFX Input plugin is mentioned in the README file, and I see no reason to include the KFX Input code in my plugin.
