### ISSUE TITLE
New autorelease causes annoying notifications

### ISSUE THREAD

**Issue by inklesspen** [noDRM/DeDRM_tools#358]
I set my notification settings on this repository to email me when there was a new release (so I would know to upgrade). However, today I have gotten seven emails about the "autorelease" built from each commit.

Unfortunately it [doesn't yet seem possible](https://github.com/orgs/community/discussions/10776) to tell github not to send notifications for pre-releases. I'm told some projects get around this by having the auto-releases built in a separate repo…

**Comment by noDRM** [comment]
Whoops, that was not my intention. I assumed that marking a release as a prerelease would not notify people. I'll disable this again and try to find a better solution to give people easy access to test versions.

**Comment by ElleKayEm** [comment]
I do really appreciate having easy access to the latest code.  But yeah it would be nice if the emails were limited somehow.

**Comment by ElleKayEm** [comment]
Maybe if you could just disable it when you're doing a bunch of things and reenable it when you're done...don't know if that's possible.

**Comment by ZolaLa9** [comment]
When going to the [Actions](https://github.com/noDRM/DeDRM_tools/actions) page, there are a whole lot of workflow runs titled "Update CI to create an automatic bet ...", each with a different package plugin # and commit. The commits are not reflected in the Master fork and when I click on the commit in the email notification, it says: "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." Do the plugins for each of those workflow runs actually contain the referenced commit, even though the commit is not part of a for outside the repository?

**Comment by noDRM** [comment]
> Maybe if you could just disable it when you're doing a bunch of things and reenable it when you're done...don't know if that's possible.

That would be possible, but A) requires me to know in advance that I'm starting to do a bunch of things (instead of just a quick change) and B) people would then still get the new notification once when I re-enable it. 

> Do the plugins for each of those workflow runs actually contain the referenced commit, even though the commit is part of an outside the repository?

The plugin used to be contained in this repository. When I tried to get the CI to work properly I did a couple force-pushes (= edited commits afterwards) to try and get everything to work properly. So the commits you see there were part of the repository at that point, but no longer are now. I know that that's bad style (should have used a branch), but running the release CI on a branch would also have changed how it works and could have caused other issues.

**Comment by noDRM** [comment]
Issue should now be fixed, there's now a secondary repo ( https://github.com/noDRM/DeDRM_tools_autorelease/releases ) that's only used for these automatic alpha releases with each commit, so as long as you don't watch that repo, you won't get these annoying notifications.

**Comment by ElleKayEm** [comment]
Thanks!
